---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Hypervisor:
    - CPU Usage:
        widget:
          type: glances
          url: http://pve.heima:61208
          username: villi
          password: Dyxr6EAbDdDGfYU68vE7
          version: 4
          metric: cpu
          chart: false
    - Memory Usage:
        widget:
          type: glances
          url: http://pve.heima:61208
          username: villi
          password: Dyxr6EAbDdDGfYU68vE7
          version: 4
          metric: memory
          chart: false
    - Network:
        widget:
          type: glances
          url: http://pve.heima:61208
          username: villi
          password: Dyxr6EAbDdDGfYU68vE7
          metric: network:enp0s31f6
    - Uptime:
        widget:
          type: glances
          url: http://pve.heima:61208
          username: villi
          password: Dyxr6EAbDdDGfYU68vE7
          metric: 

- Media:
    - Plex:
        icon: plex.png
        href: http://plex.heima:32400
        widget:
          type: plex
          url: http://plex.heima:32400
          key: "{{PLEX_TOKEN}}"

    - Sonarr:
        icon: sonarr.png
        href: http://sonarr.heima:8989
        widget:
          type: sonarr
          url: http://sonarr.heima:8989
          key: "{{SONARR_API_KEY}}"

    - Radarr:
        icon: radarr.png
        href: http://radarr.heima:7878
        widget:
          type: radarr
          url: http://radarr.heima:7878
          key: "{{RADARR_API_KEY}}"

    - Bazarr:
        icon: bazarr.png
        href: http://bazarr.heima:6767
        widget:
          type: bazarr
          url: http://bazarr.heima:6767
          key: "{{BAZARR_API_KEY}}"

    - qBittorrent:
        icon: qbittorrent.png
        href: http://qbittorrent.heima:8090
        widget:
          type: qbittorrent
          url: http://qbittorrent.heima:8090
          username: "{{QBIT_USER}}"
          password: "{{QBIT_PASS}}"

    - Overseerr:
        icon: overseerr.png
        href: http://overseerr.heima:5055
        widget:
          type: overseerr
          url: http://overseerr.heima:5055
          key: "{{OVERSEERR_API_KEY}}"

    - Tautulli:
        icon: tautulli.png
        href: http://tautulli.heima:8181
        widget:
          type: tautulli
          url: http://tautulli.heima:8181
          key: "{{TAUTULLI_API_KEY}}"
          enableUer: true

    - Prowlarr:
        icon: prowlarr.png
        href: http://prowlarr.heima:9696
        widget:
          type: prowlarr
          url: http://prowlarr.heima:9696
          key: "{{PROWLARR_API_KEY}}"
