---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

title: Pjalli's House

background: 
  image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg
  blur: sm
  saturate: 100
  brightness: 50
  opacity: 100

theme: dark
color: slate

useEqualHeights: true

layout:
  Media:
    style: row
    columns: 4
  Hypervisor:
    style: row
    columns: 4
